# Generated by Django 5.0.14 on 2026-02-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_number', models.IntegerField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('rfp_document', models.ForeignKey(limit_choices_to={'document_type': 'rfp'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.document')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source_documents', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['rfp_document', 'question_number'], name='questions_q_rfp_doc_bd9c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='questions_a_questio_fe80e9_idx'),
        ),
    ]
